# Generated by Django 3.1.12 on 2021-07-13 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, db_column='Titulo', null=True)),
                ('year', models.IntegerField(blank=True, db_column='Anno', null=True)),
                ('photo', models.ImageField(blank=True, db_column='Foto', null=True, upload_to='')),
                ('author_navigation_id', models.IntegerField(blank=True, db_column='IdAutorNavigationId', null=True)),
                ('photo_back', models.ImageField(blank=True, db_column='FotoBack', null=True, upload_to='')),
            ],
            options={
                'db_table': 'albums',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Nombre', null=True)),
                ('photo', models.ImageField(blank=True, db_column='Foto', null=True, upload_to='')),
            ],
            options={
                'db_table': 'autors',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('gender', models.TextField(blank=True, db_column='Genero', null=True)),
                ('name', models.TextField(blank=True, db_column='Nombre', null=True)),
                ('photo', models.ImageField(blank=True, db_column='Foto', null=True, upload_to='')),
                ('format', models.ForeignKey(blank=True, db_column='Formato', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie.format', to_field='format')),
            ],
            options={
                'db_table': 'coleccions',
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('interpreter', models.TextField(blank=True, db_column='Interprete', null=True)),
                ('place', models.TextField(blank=True, db_column='Lugar', null=True)),
                ('year', models.IntegerField(blank=True, db_column='Anno', null=True)),
                ('definition', models.TextField(blank=True, db_column='Definicion', null=True)),
                ('photo', models.ImageField(blank=True, db_column='Foto', null=True, upload_to='')),
            ],
            options={
                'db_table': 'conciertos',
            },
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, db_column='Titulo', null=True)),
                ('author', models.TextField(blank=True, db_column='Autor', null=True)),
                ('year', models.IntegerField(blank=True, db_column='Anno', null=True)),
                ('photo', models.ImageField(blank=True, db_column='Foto', null=True, upload_to='')),
                ('photo_back', models.ImageField(blank=True, db_column='FotoBack', null=True, upload_to='')),
            ],
            options={
                'db_table': 'dvd',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, db_column='TituloCancion', null=True)),
                ('success', models.BooleanField(blank=True, db_column='Exito', null=True)),
                ('video', models.FileField(blank=True, db_column='Video', null=True, upload_to='')),
                ('collection', models.ForeignKey(db_column='IdColeccion', on_delete=django.db.models.deletion.DO_NOTHING, to='music.collection')),
            ],
            options={
                'db_table': 'cancions',
            },
        ),
        migrations.CreateModel(
            name='DVDSong',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Nombre', null=True)),
                ('dvd', models.ForeignKey(blank=True, db_column='IdDvd', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.dvd')),
            ],
            options={
                'db_table': 'canciondvd',
            },
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, db_column='Titulo', null=True)),
                ('album', models.ForeignKey(blank=True, db_column='IdAlbum', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.album')),
            ],
            options={
                'db_table': 'cancionalbums',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.ForeignKey(blank=True, db_column='IdAutor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='music.author'),
        ),
    ]
