# Generated by Django 3.1.12 on 2021-07-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='video',
            field=models.BooleanField(blank=True, db_column='Video', null=True),
        ),
    ]
