# Generated by Django 3.1.12 on 2021-07-14 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20210714_1548'),
        ('music', '0002_auto_20210714_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='author',
            field=models.ForeignKey(blank=True, db_column='IdAutor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.author'),
        ),
        migrations.AlterField(
            model_name='albumsong',
            name='album',
            field=models.ForeignKey(blank=True, db_column='IdAlbum', null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.album'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='format',
            field=models.ForeignKey(blank=True, db_column='Formato', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.format', to_field='format'),
        ),
        migrations.AlterField(
            model_name='dvdsong',
            name='dvd',
            field=models.ForeignKey(blank=True, db_column='IdDvd', null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.dvd'),
        ),
        migrations.AlterField(
            model_name='song',
            name='collection',
            field=models.ForeignKey(db_column='IdColeccion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.collection'),
        ),
    ]
