# Generated by Django 3.1.12 on 2021-08-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20210811_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('-success', 'title')},
        ),
    ]
