# Generated by Django 3.1.12 on 2021-08-11 05:33

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20210811_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('success'), nulls_last=True), 'title')},
        ),
    ]
