# Generated by Django 3.1.12 on 2021-08-11 05:34

from django.db import migrations
import django.db.models.expressions
from music.models import Author


def remove_duplicate_from_author(apps, schema_editor):
    authors = Author.objects.all().reverse()
    for author in authors:
        if Author.objects.filter(name=author.name).count() > 1:
            author.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('music', '0007_auto_20210811_0133'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_from_author),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': (django.db.models.expressions.OrderBy(
                django.db.models.expressions.F('success'), descending=True,
                nulls_last=True), 'title')},
        ),
    ]
