# Generated by Django 3.1.12 on 2021-08-15 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20210811_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.TextField(blank=True, db_column='Nombre', null=True, unique=True),
        )
    ]
