# Generated by Django 3.1.12 on 2021-08-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20210814_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.TextField(blank=True, db_column='Nombre', null=True),
        ),
    ]
