# Generated by Django 3.1.12 on 2021-08-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20210814_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('photo', models.ImageField(upload_to='generosmusica/')),
            ],
        ),
    ]
