# Generated by Django 3.1.12 on 2021-08-17 16:42

from django.db import migrations, models

from music.models import Collection, GenderMusic


def migrate_existing_gender_from_collections(apps, schema_editor):
    genders = set(Collection.objects.values_list("gender"))
    for gender in genders:
        if gender[0]:
            music_gender, created = GenderMusic.objects.get_or_create(name=gender[0])
            if created:
                music_gender.photo = f"generosmusic/{gender[0]}.jpg"
                music_gender.save()


class Migration(migrations.Migration):
    dependencies = [
        ('music', '0012_auto_20210817_1250'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_gender_from_collections),
    ]
