# Generated by Django 3.1.12 on 2021-08-17 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_migrate_existing_gender_from_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='gender',
            field=models.ForeignKey(blank=True, db_column='Genero', null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.gendermusic', to_field='name'),
        ),
    ]
