# Generated by Django 3.1.12 on 2021-08-17 16:42

from django.db import migrations, models

from music.models import GenderMusic


def migrate_existing_gender_from_collections(apps, schema_editor):
    genders = GenderMusic.objects.all()
    for gender in genders:
        gender.photo = (
            f"{str(gender.photo).replace('generosmusic', 'generosmusica')}"
        )
        gender.save()


class Migration(migrations.Migration):
    dependencies = [
        ('music', '0014_auto_20210817_1350'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_gender_from_collections),
    ]
