# Generated by Django 3.1.12 on 2021-08-19 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_solving_error_in_gender_photo_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gendermusic',
            options={'ordering': ('name',)},
        ),
    ]
