# Generated by Django 3.2 on 2021-08-21 14:12

from django.db import migrations, models

from music.models import DVD, Author


def add_none_existing_authors_from_dvd(apps, schema_editor):
    authors = DVD.objects.all()
    for author in authors:
        if author.author is not None:
            obj, created = Author.objects.get_or_create(name=author.author)


class Migration(migrations.Migration):
    dependencies = [
        ('music', '0017_alter_author_name'),
    ]

    operations = [
        migrations.RunPython(add_none_existing_authors_from_dvd),
    ]
