# Generated by Django 3.2 on 2021-08-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_preparing_data_next_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='author',
            field=models.ForeignKey(blank=True, db_column='Autor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.author', to_field='name'),
        ),
    ]
