# Generated by Django 3.2 on 2021-08-21 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_alter_dvd_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dvdsong',
            old_name='name',
            new_name='title',
        ),
    ]
