# Generated by Django 3.2.9 on 2021-11-05 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_auto_20211104_2244'),
        ('music', '0022_alter_gendermusic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='author',
            field=models.ForeignKey(db_column='IdAutor',
                                    on_delete=django.db.models.deletion.CASCADE, to='music.author', verbose_name='Autor', default=103),
        ),
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='album',
            name='photo_back',
            field=models.ImageField(blank=True, db_column='FotoBack', null=True, upload_to='', verbose_name='Foto posterior'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(db_column='Titulo', default='Sin definir', max_length=500, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(blank=True, db_column='Anno', null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='albumsong',
            name='album',
            field=models.ForeignKey(db_column='IdAlbum', on_delete=django.db.models.deletion.CASCADE, to='music.album'),
        ),
        migrations.AlterField(
            model_name='albumsong',
            name='title',
            field=models.CharField(db_column='Titulo', default='Sin definir', max_length=500, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_column='Nombre', max_length=500, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='format',
            field=models.ForeignKey(db_column='Formato', default='No', on_delete=django.db.models.deletion.CASCADE, to='movie.format', to_field='format', verbose_name='Formato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='gender',
            field=models.ForeignKey(db_column='Genero', default='Sin definir', on_delete=django.db.models.deletion.CASCADE, to='music.gendermusic', to_field='name', verbose_name='Género'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(db_column='Nombre', default='Sin definir', max_length=500, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='definition',
            field=models.CharField(blank=True, db_column='Definicion', max_length=500, null=True, verbose_name='Definición'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='interpreter',
            field=models.CharField(db_column='Interprete', default='Sin definir', max_length=500, verbose_name='Intérprete'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concert',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='place',
            field=models.CharField(blank=True, db_column='Lugar', max_length=500, null=True, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='year',
            field=models.IntegerField(blank=True, db_column='Anno', null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='author',
            field=models.ForeignKey(db_column='Autor', default=103, on_delete=django.db.models.deletion.CASCADE, to='music.author', to_field='name', verbose_name='Autor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dvd',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='photo_back',
            field=models.ImageField(blank=True, db_column='FotoBack', null=True, upload_to='', verbose_name='Foto posterior'),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='title',
            field=models.CharField(db_column='Titulo', default='Sin definir', max_length=500, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dvd',
            name='year',
            field=models.IntegerField(blank=True, db_column='Anno', null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='dvdsong',
            name='dvd',
            field=models.ForeignKey(db_column='IdDvd', default=1, on_delete=django.db.models.deletion.CASCADE, to='music.dvd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dvdsong',
            name='title',
            field=models.CharField(db_column='Nombre', default='Sin definir', max_length=500, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gendermusic',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='gendermusic',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='generosmusica/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='song',
            name='collection',
            field=models.ForeignKey(db_column='IdColeccion', default=17, on_delete=django.db.models.deletion.CASCADE, to='music.collection', verbose_name='Colección'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='success',
            field=models.BooleanField(blank=True, db_column='Exito', null=True, verbose_name='Éxito'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(db_column='TituloCancion', default='Sin definir', max_length=500, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
