# Generated by Django 3.2.9 on 2021-11-05 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_auto_20211104_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='author',
            field=models.ForeignKey(db_column='IdAutor', on_delete=django.db.models.deletion.CASCADE, to='music.author', verbose_name='Autor'),
        ),
    ]
