# Generated by Django 3.2.9 on 2021-11-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_alter_album_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', null=True, upload_to='album/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='album',
            name='photo_back',
            field=models.ImageField(blank=True, db_column='FotoBack', null=True, upload_to='album/', verbose_name='Foto posterior'),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', null=True, upload_to='autores/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', null=True, upload_to='coleccion/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', null=True, upload_to='concierto/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', null=True, upload_to='dvd/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='photo_back',
            field=models.ImageField(blank=True, db_column='FotoBack', null=True, upload_to='dvd/', verbose_name='Foto posterior'),
        ),
    ]
