# Generated by Django 3.2.9 on 2021-11-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_auto_20211105_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', null=True, upload_to='discografia/', verbose_name='Foto'),
        ),
    ]
