# Generated by Django 3.2.9 on 2021-11-05 12:16

from django.db import migrations, models
from music.models import DVD

def update_dvd_path(apps, schema_editor):
    genders = DVD.objects.all()
    for gender in genders:
        gender.photo = (
            f"{str(gender.photo).replace('album', 'dvd')}"
        )
        gender.photo_back = (
            f"{str(gender.photo_back).replace('album', 'dvd')}"
        )
        gender.save()


class Migration(migrations.Migration):
    dependencies = [
        ('music', '0027_auto_20211105_0816'),
    ]

    operations = [
        migrations.RunPython(update_dvd_path),
    ]
