# Generated by Django 3.2.9 on 2021-11-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_alter_author_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', max_length=2500, null=True, upload_to='album/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='album',
            name='photo_back',
            field=models.ImageField(blank=True, db_column='FotoBack', max_length=2500, null=True, upload_to='album/', verbose_name='Foto posterior'),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', max_length=2500, null=True, upload_to='discografia/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', max_length=2500, null=True, upload_to='coleccion/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', max_length=2500, null=True, upload_to='concierto/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', max_length=2500, null=True, upload_to='dvd/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='photo_back',
            field=models.ImageField(blank=True, db_column='FotoBack', max_length=2500, null=True, upload_to='dvd/', verbose_name='Foto posterior'),
        ),
        migrations.AlterField(
            model_name='gendermusic',
            name='photo',
            field=models.ImageField(blank=True, max_length=2500, null=True, upload_to='generosmusica/', verbose_name='Foto'),
        ),
    ]
