# Generated by Django 3.2.9 on 2022-03-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0030_auto_20220304_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='success',
            field=models.BooleanField(db_column='Exito', default=False, verbose_name='Éxito'),
        ),
        migrations.AlterField(
            model_name='song',
            name='video',
            field=models.BooleanField(db_column='Video', default=False),
        ),
    ]
