# Generated by Django 3.2.9 on 2021-11-05 12:16

from django.db import migrations, models
from music.models import Song


def update_exito_video(apps, schema_editor):
    genders = Song.objects.all()
    for gender in genders:
        if gender.success is None:
            gender.success = False
        if gender.video is None:
            gender.video = False
        gender.save()


class Migration(migrations.Migration):
    dependencies = [
        ('music', '0031_auto_20220304_0836'),
    ]

    operations = [
        migrations.RunPython(update_exito_video),
    ]
