# Generated by Django 3.2.9 on 2022-03-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0032_auto_preparing_next_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='success',
            field=models.BooleanField(blank=True, db_column='Exito', default=False, null=True, verbose_name='Éxito'),
        ),
        migrations.AlterField(
            model_name='song',
            name='video',
            field=models.BooleanField(blank=True, db_column='Video', default=False, null=True),
        ),
    ]
