# Generated by Django 3.1.12 on 2021-07-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('name', models.TextField(blank=True, db_column='Oferta', null=True)),
                ('price', models.TextField(blank=True, db_column='Precio', null=True)),
                ('especial', models.TextField(blank=True, db_column='Especial', null=True)),
                ('description', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('type', models.TextField(blank=True, db_column='TipoOferta', null=True)),
                ('photo', models.ImageField(blank=True, db_column='Foto', null=True, upload_to='')),
            ],
            options={
                'db_table': 'ofertas',
            },
        ),
    ]
