# Generated by Django 3.2 on 2021-08-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Oferta', 'verbose_name_plural': 'Ofertas'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='especial',
            field=models.CharField(blank=True, choices=[('0', 'Videos'), ('1', 'Audios'), ('2', 'Diversos')], db_column='Especial', max_length=1, null=True),
        ),
    ]
