# Generated by Django 3.2.9 on 2021-11-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_alter_offer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='especial',
            field=models.CharField(blank=True, choices=[('P', 'Videos'), ('M', 'Reality Show / Capitulo'), ('D', 'Deporte')], db_column='Especial', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'Videos'), ('1', 'Audios'), ('2', 'Diversos')], db_column='TipoOferta', max_length=1, null=True, verbose_name='Tipo'),
        ),
    ]
