# Generated by Django 3.2.9 on 2021-12-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_alter_offer_especial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'Videos'), ('1', 'Audios'), ('2', 'Diversos')], db_column='TipoOferta', max_length=250, null=True, verbose_name='Tipo'),
        ),
    ]
