# Generated by Django 3.2.9 on 2021-12-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_alter_offer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='especial',
            field=models.CharField(blank=True, db_column='Especial', max_length=250, null=True),
        ),
    ]
