# Generated by Django 3.1.12 on 2021-07-13 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Nombre', null=True)),
                ('photo', models.ImageField(blank=True, db_column='FotoActor', null=True, upload_to='')),
                ('display', models.BooleanField(blank=True, db_column='Mostrar', null=True)),
            ],
            options={
                'db_table': 'actors',
            },
        ),
        migrations.CreateModel(
            name='ActorMovie',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('actor', models.ForeignKey(blank=True, db_column='ActorId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie.actor')),
            ],
            options={
                'db_table': 'actorpelicula',
            },
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Combo', null=True)),
                ('photo', models.ImageField(blank=True, db_column='FotoCombo', null=True, upload_to='')),
            ],
            options={
                'db_table': 'combos',
            },
        ),
        migrations.CreateModel(
            name='Documental',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('title_eng', models.TextField(blank=True, db_column='NombreIng', null=True)),
                ('title', models.TextField(blank=True, db_column='Nombre', null=True)),
                ('duration', models.TextField(blank=True, db_column='Duracion', null=True)),
                ('year', models.IntegerField(blank=True, db_column='Anno', null=True)),
                ('origen', models.TextField(blank=True, db_column='Origen', null=True)),
                ('synopsis', models.TextField(blank=True, db_column='Sinopsis', null=True)),
                ('photo', models.ImageField(blank=True, db_column='FotoDocumental', null=True, upload_to='')),
                ('definition', models.TextField(blank=True, db_column='Definicion', null=True)),
                ('language', models.TextField(blank=True, db_column='Idioma', null=True)),
                ('type', models.TextField(blank=True, db_column='TipoDocumental', null=True)),
            ],
            options={
                'db_table': 'documental',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('format', models.TextField(blank=True, db_column='Formato', null=True, unique=True)),
            ],
            options={
                'db_table': 'formatos',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Genero', null=True, unique=True)),
                ('photo', models.ImageField(blank=True, db_column='FotoGenero', null=True, upload_to='')),
            ],
            options={
                'db_table': 'generos',
            },
        ),
        migrations.CreateModel(
            name='Humor',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, db_column='Nombre', null=True)),
                ('title_eng', models.TextField(blank=True, db_column='NombreIng', null=True)),
                ('interpreter', models.TextField(blank=True, db_column='Interprete', null=True)),
                ('origen', models.TextField(blank=True, db_column='Origen', null=True)),
                ('year', models.IntegerField(blank=True, db_column='Anno', null=True)),
                ('definition', models.TextField(blank=True, db_column='Definicion', null=True)),
                ('photo', models.ImageField(blank=True, db_column='Foto', null=True, upload_to='')),
            ],
            options={
                'db_table': 'humor',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('title_eng', models.TextField(blank=True, db_column='NombreIng', null=True)),
                ('title', models.TextField(blank=True, db_column='Nombre', null=True)),
                ('sub_gender', models.TextField(blank=True, db_column='Subgenero', null=True)),
                ('duration', models.TextField(blank=True, db_column='Duracion', null=True)),
                ('year', models.IntegerField(blank=True, db_column='Anno', null=True)),
                ('origen', models.TextField(blank=True, db_column='Origen', null=True)),
                ('synopsis', models.TextField(blank=True, db_column='Sinopsis', null=True)),
                ('saga', models.TextField(blank=True, db_column='Saga', null=True)),
                ('initial', models.TextField(blank=True, db_column='Inicial', null=True)),
                ('photo', models.ImageField(blank=True, db_column='FotoPelicula', null=True, upload_to='')),
                ('definition', models.TextField(blank=True, db_column='Definicion', null=True)),
                ('language', models.TextField(blank=True, db_column='Idioma', null=True)),
                ('actor', models.ManyToManyField(blank=True, through='movie.ActorMovie', to='movie.Actor')),
                ('format', models.ForeignKey(blank=True, db_column='Formato', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie.format', to_field='format')),
                ('gender', models.ForeignKey(blank=True, db_column='Genero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie.gender', to_field='name')),
            ],
            options={
                'db_table': 'peliculas',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Nombre', null=True)),
                ('year', models.TextField(blank=True, db_column='Año', null=True)),
                ('definition', models.TextField(blank=True, db_column='Definicion', null=True)),
                ('photo', models.ImageField(blank=True, db_column='Foto', null=True, upload_to='')),
                ('format', models.ForeignKey(blank=True, db_column='Formato', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie.format', to_field='format')),
            ],
            options={
                'db_table': 'deportes',
            },
        ),
        migrations.CreateModel(
            name='Sagas',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, db_column='Saga', null=True)),
                ('movie', models.ForeignKey(blank=True, db_column='IdPelicula', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie.movie')),
            ],
            options={
                'db_table': 'sagas',
            },
        ),
        migrations.CreateModel(
            name='GenderDocumental',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, db_column='FotoGenero', null=True, upload_to='')),
                ('type', models.IntegerField(blank=True, db_column='TipoDocumental', null=True)),
                ('gender', models.ForeignKey(blank=True, db_column='Genero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie.gender', to_field='name')),
            ],
            options={
                'db_table': 'generodocumental',
            },
        ),
        migrations.CreateModel(
            name='DocumentalSeason',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('season', models.TextField(blank=True, db_column='Temporada', null=True)),
                ('chapters', models.TextField(blank=True, db_column='Capitulos', null=True)),
                ('year', models.TextField(blank=True, db_column='Anno', null=True)),
                ('doumental', models.ForeignKey(blank=True, db_column='IdDocumental', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie.documental')),
            ],
            options={
                'db_table': 'documentalestemporadas',
            },
        ),
        migrations.AddField(
            model_name='documental',
            name='format',
            field=models.ForeignKey(blank=True, db_column='Formato', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie.format', to_field='format'),
        ),
        migrations.AddField(
            model_name='documental',
            name='gender',
            field=models.ForeignKey(blank=True, db_column='Genero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie.genderdocumental'),
        ),
        migrations.CreateModel(
            name='ComboMovie',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, db_column='Titulo', null=True)),
                ('description', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('combo', models.ForeignKey(blank=True, db_column='IdCombo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie.combo')),
            ],
            options={
                'db_table': 'peliculascombos',
            },
        ),
        migrations.AddField(
            model_name='actormovie',
            name='movie',
            field=models.ForeignKey(blank=True, db_column='PeliculaId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie.movie'),
        ),
    ]
