# Generated by Django 3.1.12 on 2021-07-14 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210714_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actormovie',
            name='actor',
            field=models.ForeignKey(blank=True, db_column='ActorId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.actor'),
        ),
        migrations.AlterField(
            model_name='actormovie',
            name='movie',
            field=models.ForeignKey(blank=True, db_column='PeliculaId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.movie'),
        ),
        migrations.AlterField(
            model_name='combomovie',
            name='combo',
            field=models.ForeignKey(blank=True, db_column='IdCombo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.combo'),
        ),
        migrations.AlterField(
            model_name='documental',
            name='format',
            field=models.ForeignKey(blank=True, db_column='Formato', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.format', to_field='format'),
        ),
        migrations.AlterField(
            model_name='documental',
            name='gender',
            field=models.ForeignKey(blank=True, db_column='Genero', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.genderdocumental'),
        ),
        migrations.AlterField(
            model_name='documentalseason',
            name='doumental',
            field=models.ForeignKey(blank=True, db_column='IdDocumental', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.documental'),
        ),
        migrations.AlterField(
            model_name='genderdocumental',
            name='gender',
            field=models.ForeignKey(blank=True, db_column='Genero', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.gender', to_field='name'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='format',
            field=models.ForeignKey(blank=True, db_column='Formato', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.format', to_field='format'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='gender',
            field=models.ForeignKey(blank=True, db_column='Genero', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.gender', to_field='name'),
        ),
        migrations.AlterField(
            model_name='sagas',
            name='movie',
            field=models.ForeignKey(blank=True, db_column='IdPelicula', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.movie'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='format',
            field=models.ForeignKey(blank=True, db_column='Formato', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.format', to_field='format'),
        ),
    ]
