# Generated by Django 3.1.12 on 2021-08-11 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20210714_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('title_eng',)},
        ),
    ]
