# Generated by Django 3.1.12 on 2021-08-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20210811_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='photo',
            field=models.ImageField(blank=True, db_column='FotoGenero', null=True, upload_to='generos/'),
        ),
    ]
