# Generated by Django 3.1.12 on 2021-08-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20210815_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ('name',)},
        ),
    ]
