# Generated by Django 3.1.12 on 2021-08-16 04:32

from django.db import migrations, models
import django.db.models.deletion

from movie.models import Sagas, Movie


def remove_duplicate_from_saga(apps, schema_editor):
    sagas = Sagas.objects.all().reverse()
    for saga in sagas:
        if Sagas.objects.filter(title=saga.title).count() > 1:
            saga.delete()


def create_saga_from_movie_saga(apps, schema_editor):
    movies = Movie.objects.exclude(saga=None).all()
    for movie in movies:
        saga, created = Sagas.objects.get_or_create(title=str(movie.saga))


class Migration(migrations.Migration):
    dependencies = [
        ('movie', '0007_auto_20210815_1808'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_from_saga),
        migrations.RunPython(create_saga_from_movie_saga),
    ]
