# Generated by Django 3.1.12 on 2021-08-16 04:32

from django.db import migrations, models
import django.db.models.deletion

from movie.models import Sagas, Movie


class Migration(migrations.Migration):
    dependencies = [
        ('movie', '0008_auto_20210816_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sagas',
            name='movie',
        ),
        migrations.AlterField(
            model_name='sagas',
            name='title',
            field=models.TextField(blank=True, db_column='Saga', null=True,
                                   unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='saga',
            field=models.ForeignKey(blank=True, db_column='Saga', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='movie.sagas', to_field='title'),
        )
    ]
