# Generated by Django 3.1.12 on 2021-08-18 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20210816_0032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sagas',
            options={'ordering': ('title',)},
        ),
    ]
