# Generated by Django 3.1.12 on 2021-08-18 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20210817_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ('name',)},
        ),
    ]
