# Generated by Django 3.1.12 on 2021-08-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20210818_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genderdocumental',
            options={'ordering': ('type',)},
        ),
        migrations.AlterField(
            model_name='genderdocumental',
            name='photo',
            field=models.ImageField(blank=True, db_column='FotoGenero', null=True, upload_to='generos/Documental/'),
        ),
    ]
