# Generated by Django 3.1.12 on 2021-08-15 17:39

from django.db import migrations, models
from movie.models import GenderDocumental


def update_gender_image_path(apps, schema_editor):
    genders = GenderDocumental.objects.all()
    for gender in genders:
        if str(gender.photo) == "generos/Documental/":
            gender.photo = ""
            gender.save()


class Migration(migrations.Migration):
    dependencies = [
        ('movie', '0013_auto_20210818_1543'),
    ]

    operations = [
        migrations.RunPython(update_gender_image_path)
    ]
