# Generated by Django 3.1.12 on 2021-08-19 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_auto_20210818_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humor',
            options={'ordering': ('title_eng',)},
        ),
    ]
