# Generated by Django 3.2 on 2021-08-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_auto_20210819_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Actor', 'verbose_name_plural': 'Actores'},
        ),
        migrations.AlterModelOptions(
            name='combo',
            options={'verbose_name': 'Combo', 'verbose_name_plural': 'Combos'},
        ),
        migrations.AlterModelOptions(
            name='combomovie',
            options={'verbose_name': 'Película del Combo', 'verbose_name_plural': 'Películas del Combo'},
        ),
        migrations.AlterModelOptions(
            name='documental',
            options={'verbose_name': 'Documental', 'verbose_name_plural': 'Documentales'},
        ),
        migrations.AlterModelOptions(
            name='documentalseason',
            options={'verbose_name': 'Temporada del Documental', 'verbose_name_plural': 'Temporadas del Documental'},
        ),
        migrations.AlterModelOptions(
            name='format',
            options={'verbose_name': 'Formato', 'verbose_name_plural': 'Formatos'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ('name',), 'verbose_name': 'Género', 'verbose_name_plural': 'Géneros'},
        ),
        migrations.AlterModelOptions(
            name='genderdocumental',
            options={'ordering': ('type',), 'verbose_name': 'Género Documental', 'verbose_name_plural': 'Géneros Documentales'},
        ),
        migrations.AlterModelOptions(
            name='humor',
            options={'ordering': ('title_eng',), 'verbose_name': 'Humor', 'verbose_name_plural': 'Humor'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('title_eng',), 'verbose_name': 'Película', 'verbose_name_plural': 'Películas'},
        ),
        migrations.AlterModelOptions(
            name='sagas',
            options={'ordering': ('title',), 'verbose_name': 'Saga', 'verbose_name_plural': 'Sagas'},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ('name',), 'verbose_name': 'Deporte', 'verbose_name_plural': 'Deportes'},
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(blank=True, db_column='Nombre', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='combo',
            name='name',
            field=models.CharField(blank=True, db_column='Combo', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='combomovie',
            name='title',
            field=models.CharField(blank=True, db_column='Titulo', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documental',
            name='definition',
            field=models.CharField(blank=True, db_column='Definicion', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documental',
            name='duration',
            field=models.CharField(blank=True, db_column='Duracion', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documental',
            name='language',
            field=models.CharField(blank=True, db_column='Idioma', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documental',
            name='origen',
            field=models.CharField(blank=True, db_column='Origen', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documental',
            name='title',
            field=models.CharField(blank=True, db_column='Nombre', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documental',
            name='title_eng',
            field=models.CharField(blank=True, db_column='NombreIng', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documental',
            name='type',
            field=models.CharField(blank=True, db_column='TipoDocumental', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documentalseason',
            name='chapters',
            field=models.CharField(blank=True, db_column='Capitulos', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documentalseason',
            name='season',
            field=models.CharField(blank=True, db_column='Temporada', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documentalseason',
            name='year',
            field=models.CharField(blank=True, db_column='Anno', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='format',
            name='format',
            field=models.CharField(blank=True, db_column='Formato', max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(blank=True, db_column='Genero', max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='genderdocumental',
            name='type',
            field=models.CharField(blank=True, db_column='TipoDocumental', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='humor',
            name='definition',
            field=models.CharField(blank=True, db_column='Definicion', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='humor',
            name='interpreter',
            field=models.CharField(blank=True, db_column='Interprete', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='humor',
            name='origen',
            field=models.CharField(blank=True, db_column='Origen', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='humor',
            name='title',
            field=models.CharField(blank=True, db_column='Nombre', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='humor',
            name='title_eng',
            field=models.CharField(blank=True, db_column='NombreIng', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='humor',
            name='year',
            field=models.CharField(blank=True, db_column='Anno', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='definition',
            field=models.CharField(blank=True, db_column='Definicion', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(blank=True, db_column='Duracion', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='initial',
            field=models.CharField(blank=True, db_column='Inicial', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, db_column='Idioma', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='origen',
            field=models.CharField(blank=True, db_column='Origen', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='sub_gender',
            field=models.CharField(blank=True, db_column='Subgenero', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, db_column='Nombre', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_eng',
            field=models.CharField(blank=True, db_column='NombreIng', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sagas',
            name='title',
            field=models.CharField(blank=True, db_column='Saga', max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='definition',
            field=models.CharField(blank=True, db_column='Definicion', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(blank=True, db_column='Nombre', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='year',
            field=models.CharField(blank=True, db_column='Año', max_length=500, null=True),
        ),
    ]
