# Generated by Django 3.2 on 2021-11-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_alter_actor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='imdb',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(db_column='Nombre', default='John Doe', max_length=500, verbose_name='Nombre y apellidos'),
            preserve_default=False,
        ),
    ]
