# Generated by Django 3.2 on 2021-11-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_auto_20211101_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title_eng',
            field=models.CharField(db_column='NombreIng', default='Sin definir', max_length=500),
            preserve_default=False,
        ),
    ]
