# Generated by Django 3.2.9 on 2021-11-05 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0020_alter_movie_title_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='reviewed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='combo',
            name='name',
            field=models.CharField(db_column='Combo', max_length=500, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='photo',
            field=models.ImageField(blank=True, db_column='FotoCombo', null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='combomovie',
            name='combo',
            field=models.ForeignKey(db_column='IdCombo', on_delete=django.db.models.deletion.CASCADE, to='movie.combo'),
        ),
        migrations.AlterField(
            model_name='combomovie',
            name='description',
            field=models.TextField(blank=True, db_column='Descripcion', null=True, verbose_name='Descricción'),
        ),
        migrations.AlterField(
            model_name='combomovie',
            name='title',
            field=models.CharField(db_column='Titulo', default='Sin definir', max_length=500, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documental',
            name='definition',
            field=models.CharField(blank=True, db_column='Definicion', max_length=500, null=True, verbose_name='Definición'),
        ),
        migrations.AlterField(
            model_name='documental',
            name='duration',
            field=models.CharField(blank=True, db_column='Duracion', max_length=500, null=True, verbose_name='Duuración'),
        ),
        migrations.AlterField(
            model_name='documental',
            name='format',
            field=models.ForeignKey(blank=True, db_column='Formato', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.format', to_field='format', verbose_name='Formato'),
        ),
        migrations.AlterField(
            model_name='documental',
            name='gender',
            field=models.ForeignKey(blank=True, db_column='Genero', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.genderdocumental', verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='documental',
            name='language',
            field=models.CharField(blank=True, db_column='Idioma', max_length=500, null=True, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='documental',
            name='origen',
            field=models.CharField(blank=True, db_column='Origen', max_length=500, null=True, verbose_name='País de origen'),
        ),
        migrations.AlterField(
            model_name='documental',
            name='photo',
            field=models.ImageField(blank=True, db_column='FotoDocumental', null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='documental',
            name='synopsis',
            field=models.TextField(blank=True, db_column='Sinopsis', null=True, verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='documental',
            name='title',
            field=models.CharField(blank=True, db_column='Nombre', max_length=500, null=True, verbose_name='Título en Español'),
        ),
        migrations.AlterField(
            model_name='documental',
            name='title_eng',
            field=models.CharField(db_column='NombreIng', default="Sin definir", max_length=500, verbose_name='Título en Inglés'),
        ),
        migrations.AlterField(
            model_name='documental',
            name='type',
            field=models.CharField(blank=True, db_column='TipoDocumental', max_length=500, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='documental',
            name='year',
            field=models.IntegerField(blank=True, db_column='Anno', null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='documentalseason',
            name='chapters',
            field=models.CharField(blank=True, db_column='Capitulos', max_length=500, null=True, verbose_name='Capítulos'),
        ),
        migrations.AlterField(
            model_name='documentalseason',
            name='season',
            field=models.CharField(blank=True, db_column='Temporada', max_length=500, null=True, verbose_name='Temporada'),
        ),
        migrations.AlterField(
            model_name='documentalseason',
            name='year',
            field=models.CharField(blank=True, db_column='Anno', max_length=500, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='format',
            name='format',
            field=models.CharField(db_column='Formato', max_length=500, unique=True, verbose_name='Formato'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(db_column='Genero', max_length=500, unique=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='photo',
            field=models.ImageField(blank=True, db_column='FotoGenero', null=True, upload_to='generos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='genderdocumental',
            name='gender',
            field=models.ForeignKey(blank=True, db_column='Genero', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.gender', to_field='name', verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='genderdocumental',
            name='photo',
            field=models.ImageField(blank=True, db_column='FotoGenero', null=True, upload_to='generos/Documental/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='genderdocumental',
            name='type',
            field=models.CharField(blank=True, db_column='TipoDocumental', max_length=500, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='humor',
            name='definition',
            field=models.CharField(blank=True, db_column='Definicion', max_length=500, null=True, verbose_name='Definición'),
        ),
        migrations.AlterField(
            model_name='humor',
            name='interpreter',
            field=models.CharField(blank=True, db_column='Interprete', max_length=500, null=True, verbose_name='Intérprete'),
        ),
        migrations.AlterField(
            model_name='humor',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='humor',
            name='title',
            field=models.CharField(blank=True, db_column='Nombre', max_length=500, null=True, verbose_name='Título en Español'),
        ),
        migrations.AlterField(
            model_name='humor',
            name='title_eng',
            field=models.CharField(db_column='NombreIng', max_length=500, verbose_name='Título en Inglés'),
        ),
        migrations.AlterField(
            model_name='humor',
            name='year',
            field=models.CharField(blank=True, db_column='Anno', max_length=500, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(blank=True, through='movie.ActorMovie', to='movie.Actor', verbose_name='Elenco de la película'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='definition',
            field=models.CharField(blank=True, db_column='Definicion', max_length=500, null=True, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(blank=True, db_column='Duracion', max_length=500, null=True, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='format',
            field=models.ForeignKey(db_column='Formato', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.format', to_field='format', verbose_name='Formato'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='gender',
            field=models.ForeignKey(blank=True, db_column='Genero', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.gender', to_field='name', verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, db_column='Idioma', max_length=500, null=True, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='origen',
            field=models.CharField(blank=True, db_column='Origen', max_length=500, null=True, verbose_name='País de origen'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='photo',
            field=models.ImageField(blank=True, db_column='FotoPelicula', null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='saga',
            field=models.ForeignKey(blank=True, db_column='Saga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.sagas', to_field='title', verbose_name='Saga'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='sub_gender',
            field=models.CharField(blank=True, db_column='Subgenero', max_length=500, null=True, verbose_name='Subgéneros'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(blank=True, db_column='Sinopsis', null=True, verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(blank=True, db_column='Nombre', max_length=500, null=True, verbose_name='Título en Español'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_eng',
            field=models.CharField(db_column='NombreIng', max_length=500, verbose_name='Título en Inglés'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, db_column='Anno', null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='sagas',
            name='title',
            field=models.CharField(db_column='Saga', max_length=500, unique=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='definition',
            field=models.CharField(blank=True, db_column='Definicion', max_length=500, null=True, verbose_name='Definición'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='format',
            field=models.ForeignKey(blank=True, db_column='Formato', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.format', to_field='format', verbose_name='Formato'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(db_column='Nombre', max_length=500, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='year',
            field=models.CharField(blank=True, db_column='Año', max_length=500, null=True, verbose_name='Año'),
        ),
    ]
