# Generated by Django 3.2.9 on 2021-11-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_auto_20211104_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combomovie',
            name='description',
            field=models.TextField(blank=True, db_column='Descripcion', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='documental',
            name='title_eng',
            field=models.CharField(db_column='NombreIng', max_length=500, verbose_name='Título en Inglés'),
        ),
    ]
