# Generated by Django 3.2.9 on 2021-11-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_auto_20211104_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='photo',
            field=models.ImageField(blank=True, db_column='FotoCombo', null=True, upload_to='combos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='documental',
            name='photo',
            field=models.ImageField(blank=True, db_column='FotoDocumental', null=True, upload_to='documental/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='humor',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', null=True, upload_to='humor/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='photo',
            field=models.ImageField(blank=True, db_column='FotoPelicula', null=True, upload_to='peliculas/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', null=True, upload_to='deporte/', verbose_name='Foto'),
        ),
    ]
