# Generated by Django 3.2.9 on 2021-11-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0023_auto_20211105_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.ImageField(blank=True, db_column='FotoActor', max_length=2500, null=True, upload_to='actores/'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='photo',
            field=models.ImageField(blank=True, db_column='FotoCombo', max_length=2500, null=True, upload_to='combos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='documental',
            name='photo',
            field=models.ImageField(blank=True, db_column='FotoDocumental', max_length=2500, null=True, upload_to='documental/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='photo',
            field=models.ImageField(blank=True, db_column='FotoGenero', max_length=2500, null=True, upload_to='generos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='genderdocumental',
            name='photo',
            field=models.ImageField(blank=True, db_column='FotoGenero', max_length=2500, null=True, upload_to='generos/Documental/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='humor',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', max_length=2500, null=True, upload_to='humor/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='photo',
            field=models.ImageField(blank=True, db_column='FotoPelicula', max_length=2500, null=True, upload_to='peliculas/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', max_length=2500, null=True, upload_to='deporte/', verbose_name='Foto'),
        ),
    ]
