# Generated by Django 3.2.9 on 2021-11-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0025_rename_doumental_documentalseason_documental'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ('name',), 'verbose_name': 'Actor', 'verbose_name_plural': 'Actores'},
        ),
        migrations.AlterModelOptions(
            name='combo',
            options={'ordering': ('name',), 'verbose_name': 'Combo', 'verbose_name_plural': 'Combos'},
        ),
        migrations.AlterModelOptions(
            name='documental',
            options={'ordering': ('title_eng',), 'verbose_name': 'Documental', 'verbose_name_plural': 'Documentales'},
        ),
    ]
