# Generated by Django 3.2.9 on 2021-12-02 01:22

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0026_auto_20211126_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='origen',
            field=django_countries.fields.CountryField(blank=True, db_column='Origen', max_length=500, null=True, verbose_name='País de origen'),
        ),
    ]
