# Generated by Django 3.2.9 on 2021-12-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0029_auto_20211202_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documental',
            name='duration',
            field=models.CharField(blank=True, db_column='Duracion', max_length=500, null=True, verbose_name='Duración'),
        ),
    ]
