# Generated by Django 3.2.9 on 2021-12-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0030_alter_documental_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documental',
            name='year',
            field=models.CharField(blank=True, db_column='Anno', max_length=500, null=True, verbose_name='Año'),
        ),
    ]
