# Generated by Django 3.2.9 on 2021-12-05 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0032_alter_documental_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actor',
        ),
        migrations.DeleteModel(
            name='ActorMovie',
        ),
    ]
