# Generated by Django 3.2.9 on 2021-12-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0035_alter_movie_definition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='initial',
        ),
        migrations.AlterField(
            model_name='movie',
            name='definition',
            field=models.CharField(blank=True, choices=[('HD', 'HD'), ('FULL-HD', 'FULL-HD')], db_column='Definicion', max_length=500, null=True, verbose_name='Definicion'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, choices=[('Subt-Esp', 'Subt-Esp'), ('Español', 'Español')], db_column='Idioma', max_length=500, null=True, verbose_name='Idioma'),
        ),
    ]
