# Generated by Django 3.2.9 on 2021-12-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0036_auto_20211205_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documental',
            name='language',
            field=models.CharField(blank=True, choices=[('Subt-Esp', 'Subt-Esp'), ('Español', 'Español')], db_column='Idioma', max_length=500, null=True, verbose_name='Idioma'),
        ),
    ]
