# Generated by Django 3.2.9 on 2022-03-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0037_alter_documental_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Película', 'verbose_name_plural': 'Películas'},
        ),
    ]
