# Generated by Django 3.2.9 on 2022-03-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0038_alter_movie_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documental',
            name='origen',
            field=models.CharField(blank=True, db_column='Origen', max_length=500, null=True, verbose_name='País de origen'),
        ),
        migrations.AlterField(
            model_name='humor',
            name='origen',
            field=models.CharField(blank=True, db_column='Origen', max_length=500, null=True, verbose_name='País de origen'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='origen',
            field=models.CharField(blank=True, db_column='Origen', max_length=500, null=True, verbose_name='País de origen'),
        ),
    ]
