# Generated by Django 3.2.9 on 2022-03-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0039_auto_20220301_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documental',
            name='origen',
            field=models.CharField(db_column='Origen', default='USA', max_length=500, verbose_name='País de origen'),
        ),
        migrations.AlterField(
            model_name='humor',
            name='origen',
            field=models.CharField(db_column='Origen', default='USA', max_length=500, verbose_name='País de origen'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='origen',
            field=models.CharField(db_column='Origen', default='USA', max_length=500, verbose_name='País de origen'),
        ),
    ]
