# Generated by Django 3.2.9 on 2022-03-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0040_auto_20220301_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documental',
            name='definition',
            field=models.CharField(blank=True, choices=[('HD', 'HD'), ('FULL-HD', 'FULL-HD')], db_column='Definicion', max_length=500, null=True, verbose_name='Definición'),
        ),
        migrations.AlterField(
            model_name='humor',
            name='definition',
            field=models.CharField(blank=True, choices=[('HD', 'HD'), ('FULL-HD', 'FULL-HD')], db_column='Definicion', max_length=500, null=True, verbose_name='Definición'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='definition',
            field=models.CharField(blank=True, choices=[('HD', 'HD'), ('FULL-HD', 'FULL-HD')], db_column='Definicion', max_length=500, null=True, verbose_name='Definición'),
        ),
    ]
