# Generated by Django 3.2.9 on 2021-11-05 12:16

from django.db import migrations, models
from movie.models import Movie
from serial.models import Serial


def update_exito_video(apps, schema_editor):
    genders = Movie.objects.all()
    for gender in genders:
        if gender.origen == "US":
            gender.origen = "USA"
        if gender.origen == "CU":
            gender.origen = "Cuba"
        gender.save()
    genders = Serial.objects.all()
    for gender in genders:
        if gender.origen == "US":
            gender.origen = "USA"
        if gender.origen == "CU":
            gender.origen = "Cuba"
        gender.save()


class Migration(migrations.Migration):
    dependencies = [
        ('movie', '0041_auto_20220301_2302'),
    ]

    operations = [
        migrations.RunPython(update_exito_video),
    ]
