# Generated by Django 3.2.9 on 2021-11-05 12:16

from django.db import migrations, models
from movie.models import Movie
from serial.models import Serial


def update_exito_video(apps, schema_editor):
    genders = Movie.objects.all()
    for gender in genders:
        if gender.origen == "TH":
            gender.origen = "Tailandia"
        if gender.origen == "TR":
            gender.origen = "Turquia"
        if gender.origen == "TN":
            gender.origen = "Tunisia"
        if gender.origen == "AR":
            gender.origen = "Argentina"
        if gender.origen == "IT":
            gender.origen = "Italia"
        if gender.origen == "AU":
            gender.origen = "Australia"
        if gender.origen == "BE":
            gender.origen = "Belgica"
        if gender.origen == "BR":
            gender.origen = "Brasil"
        if gender.origen == "CA":
            gender.origen = "Canada"
        if gender.origen == "CN":
            gender.origen = "Corea"
        if gender.origen == "KR":
            gender.origen = "Corea"
        if gender.origen == "CO":
            gender.origen = "Colombia"
        if gender.origen == "CZ":
            gender.origen = "Republica Checa"
        if gender.origen == "DE":
            gender.origen = "Dinamarca"
        if gender.origen == "DO":
            gender.origen = "Republica Dominicana"
        if gender.origen == "DR":
            gender.origen = "Dinamarca"
        if gender.origen == "ES":
            gender.origen = "España"
        if gender.origen == "FR":
            gender.origen = "Francia"
        if gender.origen == "GB":
            gender.origen = "Reino Unido"
        if gender.origen == "ME":
            gender.origen = "Mexico"
        if gender.origen == "MX":
            gender.origen = "Mexico"
        if gender.origen == "VE":
            gender.origen = "Venezuela"
        if gender.origen == "HD":
            gender.origen = "Holanda"
        if gender.origen == "HK":
            gender.origen = "Hong Kong"
        if gender.origen == "ID":
            gender.origen = "Indonesia"
        if gender.origen == "IN":
            gender.origen = "India"
        if gender.origen == "JP":
            gender.origen = "Japon"
        if gender.origen == "sue":
            gender.origen = "Suecia"
        if gender.origen == "TW":
            gender.origen = "Taiwan"
        if gender.origen == "NL":
            gender.origen = "Noruega"
        if gender.origen == "PA":
            gender.origen = "Paraguay"
        if gender.origen == "PE":
            gender.origen = "Peru"
        if gender.origen == "PL":
            gender.origen = "Polonia"
        if gender.origen == "RU":
            gender.origen = "Rusia"
        if gender.origen == "SE":
            gender.origen = "Serbia"
        if gender.origen == "SK":
            gender.origen = "Eslovaquia"
        
        gender.save()
    genders = Serial.objects.all()
    for gender in genders:
        if gender.origen == "TH":
            gender.origen = "Tailandia"
        if gender.origen == "TR":
            gender.origen = "Turquia"
        if gender.origen == "TN":
            gender.origen = "Tunisia"
        if gender.origen == "AR":
            gender.origen = "Argentina"
        if gender.origen == "IT":
            gender.origen = "Italia"
        if gender.origen == "AU":
            gender.origen = "Australia"
        if gender.origen == "BE":
            gender.origen = "Belgica"
        if gender.origen == "BR":
            gender.origen = "Brasil"
        if gender.origen == "CA":
            gender.origen = "Canada"
        if gender.origen == "CN":
            gender.origen = "Corea"
        if gender.origen == "KR":
            gender.origen = "Corea"
        if gender.origen == "CO":
            gender.origen = "Colombia"
        if gender.origen == "CZ":
            gender.origen = "Republica Checa"
        if gender.origen == "DE":
            gender.origen = "Dinamarca"
        if gender.origen == "DO":
            gender.origen = "Republica Dominicana"
        if gender.origen == "DR":
            gender.origen = "Dinamarca"
        if gender.origen == "ES":
            gender.origen = "España"
        if gender.origen == "FR":
            gender.origen = "Francia"
        if gender.origen == "GB":
            gender.origen = "Reino Unido"
        if gender.origen == "ME":
            gender.origen = "Mexico"
        if gender.origen == "MX":
            gender.origen = "Mexico"
        if gender.origen == "VE":
            gender.origen = "Venezuela"
        if gender.origen == "HD":
            gender.origen = "Holanda"
        if gender.origen == "HK":
            gender.origen = "Hong Kong"
        if gender.origen == "ID":
            gender.origen = "Indonesia"
        if gender.origen == "IN":
            gender.origen = "India"
        if gender.origen == "JP":
            gender.origen = "Japon"
        if gender.origen == "sue":
            gender.origen = "Suecia"
        if gender.origen == "TW":
            gender.origen = "Taiwan"
        if gender.origen == "NL":
            gender.origen = "Noruega"
        if gender.origen == "PA":
            gender.origen = "Paraguay"
        if gender.origen == "PE":
            gender.origen = "Peru"
        if gender.origen == "PL":
            gender.origen = "Polonia"
        if gender.origen == "RU":
            gender.origen = "Rusia"
        if gender.origen == "SE":
            gender.origen = "Serbia"
        if gender.origen == "SK":
            gender.origen = "Eslovaquia"
        gender.save()


class Migration(migrations.Migration):
    dependencies = [
        ('movie', '0043_auto_preparing_next_migration'),
    ]

    operations = [
        migrations.RunPython(update_exito_video),
    ]
