# Generated by Django 3.1.12 on 2021-11-04 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_license_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
