# Generated by Django 3.2.9 on 2021-11-05 02:23

import datetime
from django.db import migrations
from django.utils.timezone import utc
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20211104_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='expired',
            field=pgcrypto.fields.EncryptedDateTimeField(charset='utf-8', check_armor=True, cipher='aes', default=datetime.datetime(2021, 12, 5, 2, 21, 34, 817042, tzinfo=utc), versioned=False),
        ),
    ]
