# Generated by Django 3.2.9 on 2021-12-24 06:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15), help_text='Teléfonos separados por coma.', size=2, verbose_name='Teléfonos'),
        ),
    ]
