# Generated by Django 3.1.12 on 2021-07-14 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210714_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(blank=True, db_column='IdCategoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.category'),
        ),
    ]
