# Generated by Django 3.1.12 on 2021-08-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gamecapture_imagefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecapture',
            name='capture',
        ),
        migrations.AddField(
            model_name='gamecapture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='ImageFile',
        ),
    ]
