# Generated by Django 3.1.12 on 2021-08-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20210808_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecapture',
            name='image',
            field=models.ImageField(blank=True, max_length=2500, null=True, upload_to=''),
        ),
    ]
