# Generated by Django 3.1.12 on 2021-08-11 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20210808_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('name',)},
        ),
    ]
