# Generated by Django 3.2 on 2021-08-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20210814_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Categoría del Juego', 'verbose_name_plural': 'Categorías de los Juegos'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('name',), 'verbose_name': 'Juego', 'verbose_name_plural': 'Juegos'},
        ),
        migrations.AlterModelOptions(
            name='gamecapture',
            options={'verbose_name': 'Captura del Juego', 'verbose_name_plural': 'Capturas del Juego'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, db_column='Nombre', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='capture',
            field=models.CharField(blank=True, db_column='Capturas', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='size',
            field=models.CharField(blank=True, db_column='Tamano', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(blank=True, db_column='Tipo', max_length=500, null=True),
        ),
    ]
