# Generated by Django 3.2 on 2021-11-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20210823_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecapture',
            name='image',
            field=models.ImageField(blank=True, max_length=2500, null=True, upload_to='juegos/capturas/'),
        ),
    ]
