# Generated by Django 3.2.9 on 2021-11-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_game_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecapture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
