# Generated by Django 3.2.9 on 2021-11-05 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_gamecapture_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='capture',
        ),
        migrations.AddField(
            model_name='game',
            name='reviewed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_column='Nombre', default='Sin definir', max_length=500, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, db_column='FotoCategoria', null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(blank=True, db_column='IdCategoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(db_column='Nombre', default='Sin definir', max_length=500, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', max_length=500, null=True, upload_to='juegos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='game',
            name='requirement',
            field=models.TextField(blank=True, db_column='Requisitos', null=True, verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='game',
            name='size',
            field=models.CharField(blank=True, db_column='Tamano', max_length=500, null=True, verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='game',
            name='synopsis',
            field=models.TextField(blank=True, db_column='Sinopsis', null=True, verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(blank=True, db_column='Tipo', max_length=500, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.IntegerField(blank=True, db_column='Anno', null=True, verbose_name='Año'),
        ),
    ]
