# Generated by Django 3.2.9 on 2021-11-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20211104_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, db_column='FotoCategoria', max_length=2500, null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='game',
            name='photo',
            field=models.ImageField(blank=True, db_column='Foto', max_length=2500, null=True, upload_to='juegos/', verbose_name='Foto'),
        ),
    ]
