# Generated by Django 3.2.9 on 2021-11-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_auto_20211105_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='manual',
            field=models.FileField(blank=True, db_column='Manual', max_length=2500, null=True, upload_to='juegos/manual/'),
        ),
    ]
