# Generated by Django 3.2.9 on 2021-12-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_game_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecapture',
            name='image',
            field=models.ImageField(default='juegos/capturas/NoImagen.png', max_length=2500, upload_to='juegos/capturas/'),
            preserve_default=False,
        ),
    ]
