# Generated by Django 3.2.9 on 2022-03-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_auto_20220302_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, db_column='FotoCategoria', max_length=2500, null=True, upload_to='juegos/tarjetas/', verbose_name='Foto Inicial'),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo_back',
            field=models.ImageField(blank=True, db_column='FotoCategoriaBack', max_length=2500, null=True, upload_to='juegos/tarjetas/', verbose_name='Foto Posterior'),
        ),
    ]
