# Generated by Django 3.1.12 on 2021-07-13 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorSeries',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('actor', models.ForeignKey(blank=True, db_column='ActorId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie.actor')),
            ],
            options={
                'db_table': 'actorserie',
            },
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('type', models.TextField(blank=True, db_column='Tipo', null=True)),
                ('title', models.TextField(blank=True, db_column='Titulo', null=True)),
                ('title_eng', models.TextField(blank=True, db_column='TituloIng', null=True)),
                ('origen', models.TextField(blank=True, db_column='Origen', null=True)),
                ('synopsis', models.TextField(blank=True, db_column='Sinopsis', null=True)),
                ('photo', models.ImageField(blank=True, db_column='FotoSerie', null=True, upload_to='')),
                ('initial', models.TextField(blank=True, db_column='Inicial', null=True)),
                ('in_transmission', models.BooleanField(blank=True, db_column='EnCurso', null=True)),
                ('actor', models.ManyToManyField(blank=True, through='serial.ActorSeries', to='movie.Actor')),
                ('gender', models.ForeignKey(blank=True, db_column='Genero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie.gender', to_field='name')),
            ],
            options={
                'db_table': 'series',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('number', models.TextField(blank=True, db_column='Temporada', null=True)),
                ('chapters', models.TextField(blank=True, db_column='Capitulos', null=True)),
                ('definition', models.TextField(blank=True, db_column='Definicion', null=True)),
                ('year', models.TextField(blank=True, db_column='Anno', null=True)),
                ('language', models.TextField(blank=True, db_column='Idioma', null=True)),
                ('format', models.ForeignKey(blank=True, db_column='Formato', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie.format', to_field='format')),
                ('series', models.ForeignKey(db_column='IdSerie',
                                             on_delete=django.db.models.deletion.DO_NOTHING, to='serial.serial')),
            ],
            options={
                'db_table': 'seriestemporadas',
            },
        ),
        migrations.AddField(
            model_name='actorseries',
            name='series',
            field=models.ForeignKey(blank=True, db_column='SerieId',
                                    null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, to='serial.serial'),
        ),
    ]
