# Generated by Django 3.1.12 on 2021-07-14 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20210714_1548'),
        ('serial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorseries',
            name='actor',
            field=models.ForeignKey(blank=True, db_column='ActorId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.actor'),
        ),
        migrations.AlterField(
            model_name='actorseries',
            name='series',
            field=models.ForeignKey(blank=True, db_column='SerieId',
                                    null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='serial.serial'),
        ),
        migrations.AlterField(
            model_name='season',
            name='format',
            field=models.ForeignKey(blank=True, db_column='Formato', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.format', to_field='format'),
        ),
        migrations.AlterField(
            model_name='season',
            name='series',
            field=models.ForeignKey(db_column='IdSerie', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='serial.serial'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='gender',
            field=models.ForeignKey(blank=True, db_column='Genero', null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.gender', to_field='name'),
        ),
    ]
