# Generated by Django 3.1.12 on 2021-08-11 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0002_auto_20210714_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serial',
            options={'ordering': ('title_eng',)},
        ),
    ]
