# Generated by Django 3.2 on 2021-08-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0003_auto_20210811_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'Temporada de la serie', 'verbose_name_plural': 'Temporadas de la serie'},
        ),
        migrations.AlterModelOptions(
            name='serial',
            options={'ordering': ('title_eng',), 'verbose_name': 'Serie', 'verbose_name_plural': 'Series'},
        ),
        migrations.AlterField(
            model_name='season',
            name='chapters',
            field=models.CharField(blank=True, db_column='Capitulos', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='definition',
            field=models.CharField(blank=True, db_column='Definicion', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='language',
            field=models.CharField(blank=True, db_column='Idioma', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='number',
            field=models.CharField(blank=True, db_column='Temporada', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.CharField(blank=True, db_column='Anno', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='initial',
            field=models.CharField(blank=True, db_column='Inicial', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='origen',
            field=models.CharField(blank=True, db_column='Origen', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='synopsis',
            field=models.CharField(blank=True, db_column='Sinopsis', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='title',
            field=models.CharField(blank=True, db_column='Titulo', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='title_eng',
            field=models.CharField(blank=True, db_column='TituloIng', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='serial',
            name='type',
            field=models.CharField(blank=True, db_column='Tipo', max_length=500, null=True),
        ),
    ]
