# Generated by Django 3.2 on 2021-11-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0004_auto_20210823_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='film_affinity',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='serial',
            name='imdb',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
