# Generated by Django 3.2.9 on 2021-11-05 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_auto_20211104_2244'),
        ('serial', '0005_auto_20211101_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='chapters',
            field=models.CharField(blank=True, db_column='Capitulos', max_length=500, null=True, verbose_name='Capítulos'),
        ),
        migrations.AlterField(
            model_name='season',
            name='definition',
            field=models.CharField(blank=True, db_column='Definicion', max_length=500, null=True, verbose_name='Definición'),
        ),
        migrations.AlterField(
            model_name='season',
            name='format',
            field=models.ForeignKey(db_column='Formato', default='No', on_delete=django.db.models.deletion.CASCADE, to='movie.format', to_field='format'),
        ),
        migrations.AlterField(
            model_name='season',
            name='language',
            field=models.CharField(blank=True, db_column='Idioma', max_length=500, null=True, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='season',
            name='number',
            field=models.CharField(db_column='Temporada', default='Temporada 1', max_length=500, verbose_name='Temporada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='season',
            name='series',
            field=models.ForeignKey(db_column='IdSerie', on_delete=django.db.models.deletion.CASCADE, to='serial.serial'),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.CharField(blank=True, db_column='Anno', max_length=500, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='actor',
            field=models.ManyToManyField(blank=True, through='serial.ActorSeries', to='movie.Actor', verbose_name='Elenco'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='gender',
            field=models.ForeignKey(db_column='Genero', on_delete=django.db.models.deletion.CASCADE, to='movie.gender', to_field='name', verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='in_transmission',
            field=models.BooleanField(blank=True, db_column='EnCurso', null=True, verbose_name='En curso'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='origen',
            field=models.CharField(blank=True, db_column='Origen', max_length=500, null=True, verbose_name='País de Origen'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='photo',
            field=models.ImageField(blank=True, db_column='FotoSerie', null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='synopsis',
            field=models.CharField(blank=True, db_column='Sinopsis', max_length=500, null=True, verbose_name='Sinopsis'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='title',
            field=models.CharField(blank=True, db_column='Titulo', max_length=500, null=True, verbose_name='Título en Español'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='title_eng',
            field=models.CharField(db_column='TituloIng', default='Sin definir', max_length=500, verbose_name='Título en Inglés'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serial',
            name='type',
            field=models.CharField(blank=True, db_column='Tipo', max_length=500, null=True, verbose_name='Tipo'),
        ),
    ]
