# Generated by Django 3.2.9 on 2021-11-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0009_auto_20211110_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='synopsis',
            field=models.CharField(blank=True, db_column='Sinopsis', max_length=2500, null=True, verbose_name='Sinopsis'),
        ),
    ]
