# Generated by Django 3.2.9 on 2021-11-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0010_alter_serial_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='synopsis',
            field=models.TextField(blank=True, db_column='Sinopsis', null=True, verbose_name='Sinopsis'),
        ),
    ]
