# Generated by Django 3.2.9 on 2021-12-02 08:15

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0011_alter_serial_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='origen',
            field=django_countries.fields.CountryField(blank=True, db_column='Origen', max_length=500, null=True, verbose_name='País de origen'),
        ),
    ]
