# Generated by Django 3.2.9 on 2021-12-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0037_alter_documental_language'),
        ('serial', '0013_auto_20211206_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='actor',
            field=models.ManyToManyField(blank=True, to='movie.Actor', verbose_name='Elenco'),
        ),
    ]
