# Generated by Django 3.2.9 on 2022-03-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0014_serial_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novela',
            fields=[
            ],
            options={
                'verbose_name': 'Novela',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('serial.serial',),
        ),
    ]
