# Generated by Django 3.2.9 on 2022-03-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0015_novela'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serial',
            options={'verbose_name': 'Serie', 'verbose_name_plural': 'Series'},
        ),
    ]
