# Generated by Django 3.2.9 on 2022-03-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0016_alter_serial_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='origen',
            field=models.CharField(blank=True, db_column='Origen', max_length=500, null=True, verbose_name='País de origen'),
        ),
    ]
