# Generated by Django 3.2.9 on 2022-03-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0017_alter_serial_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='origen',
            field=models.CharField(db_column='Origen', default='USA', max_length=500, verbose_name='País de origen'),
        ),
    ]
