# Generated by Django 3.2.9 on 2022-03-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0019_alter_season_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='language',
            field=models.CharField(blank=True, choices=[('Subt-Esp', 'Subt-Esp'), ('Español', 'Español')], db_column='Idioma', max_length=500, null=True, verbose_name='Idioma'),
        ),
    ]
