# Generated by Django 3.2.9 on 2022-03-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serial', '0020_alter_season_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ('number',), 'verbose_name': 'Temporada de la serie', 'verbose_name_plural': 'Temporadas de la serie'},
        ),
    ]
